const fs = require('fs');
const path = 'C:/Users/Geovane TI/Documents/automatizador-pdf/temas.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));
const tema = data.find(t => t.id === 2);
if (!tema) throw new Error('ID 2 não encontrado');
const caps = tema.estrutura.capitulos;
function add(pt, en, prompt, html){ caps.push([pt,en,false,prompt,html]); }
add(
  'IA e Manipulação da Realidade: Quando Não Sabemos Mais o que é Verdade',
  'AI and Reality Manipulation: When We No Longer Know What Is True',
  'Escreva um capítulo profundo sobre deepfakes, geração sintética de voz, imagem e vídeo, manipulação de opinião pública, confiança social, crise de evidência e impacto político e psicológico de um mundo em que a verdade visual deixa de ser confiável.',
  `<h2>IA e Manipulação da Realidade: Quando Não Sabemos Mais o que é Verdade</h2><p>Durante muito tempo, ver era quase sinônimo de acreditar. Uma foto, um vídeo, um áudio ou um registro visual carregavam um peso especial de prova. Mesmo quando existia edição, o esforço para falsificar a realidade em alto nível era caro, demorado e relativamente restrito. A inteligência artificial muda esse cenário de forma radical. Hoje, vozes podem ser clonadas, rostos podem ser simulados, vídeos podem ser fabricados e cenas completas podem ser geradas com um grau crescente de verossimilhança. Isso não afeta apenas mídia e entretenimento. Afeta a própria confiança coletiva.</p><p>O problema não está só na existência de conteúdo falso. O problema está no colapso da evidência intuitiva. Quando qualquer registro pode ser forjado de forma convincente, a sociedade perde um de seus apoios básicos de coordenação: a confiança mínima no que se vê e no que se ouve. Isso é perigoso em escala pessoal, porque reputações podem ser destruídas por montagens realistas. E é ainda mais perigoso em escala política, porque uma população confusa é mais fácil de manipular, dividir e cansar.</p><p>Deepfakes e conteúdos sintéticos não funcionam apenas pela mentira direta. Eles funcionam também pelo ruído. Mesmo quando uma gravação é real, basta que exista a possibilidade social de fraude para que pessoas interessadas neguem a autenticidade. Isso cria um ambiente em que a verdade precisa se defender o tempo todo, enquanto a mentira só precisa semear dúvida. É uma inversão poderosa: a manipulação deixa de depender apenas de fabricar fatos falsos e passa a depender de enfraquecer a noção de prova.</p><p>Há ainda um efeito psicológico importante. Em ambientes saturados por imagens artificiais, as pessoas tendem a oscilar entre credulidade impulsiva e ceticismo absoluto. Nos dois casos, perdem. Se acreditam em tudo, tornam-se alvos fáceis. Se desacreditam de tudo, perdem referências comuns. Democracias, sistemas jurídicos, jornalismo e relações pessoais dependem de algum grau de realidade compartilhada. Sem isso, cresce o terreno para narrativas oportunistas e para o esgotamento moral de quem já não sabe em que confiar.</p><p>O desafio, portanto, não é apenas técnico. É cultural e institucional. Precisaremos de verificação mais robusta, educação midiática mais séria, ferramentas de autenticação, plataformas mais responsáveis e uma sociedade menos inocente diante do poder das imagens. A pergunta central do futuro talvez não seja apenas “o que aconteceu?”, mas “como podemos provar, com segurança, que isso realmente aconteceu?”.</p>`
);
add(
  'A Guerra dos Dados: O Novo Petróleo do Século XXI',
  'The Data War: The New Oil of the 21st Century',
  'Escreva um capítulo robusto sobre dados como recurso estratégico. Aborde coleta em massa, vigilância comercial, competição geopolítica, economia de atenção, previsão comportamental, soberania digital e disputa entre empresas e Estados pelo controle informacional.',
  `<h2>A Guerra dos Dados: O Novo Petróleo do Século XXI</h2><p>Se o petróleo definiu grande parte da geopolítica do século XX, os dados ocupam hoje uma posição parecida no tabuleiro do século XXI. Eles alimentam modelos de inteligência artificial, publicidade, previsão de comportamento, segurança, logística, consumo, crédito, plataformas e sistemas públicos. Quem controla fluxos massivos de dados não possui apenas informação. Possui capacidade de previsão, influência e vantagem competitiva em escala.</p><p>A coleta de dados deixou de ser algo periférico. Ela se tornou parte do funcionamento normal de aplicativos, redes, serviços financeiros, sistemas urbanos, saúde digital, comércio eletrônico e comunicação cotidiana. Cada clique, deslocamento, busca, pausa, compra, curtida e padrão de navegação se transforma em insumo econômico. O usuário, muitas vezes, imagina que está apenas usando uma ferramenta. Na prática, também está sendo convertido em matéria-prima estatística.</p><p>Isso cria uma disputa silenciosa por soberania informacional. Grandes empresas querem dados para treinar modelos, vender previsibilidade e capturar mercado. Estados querem dados para segurança, controle, planejamento e vantagem estratégica. Plataformas querem manter usuários engajados o suficiente para extrair mais sinais comportamentais. E, no meio disso tudo, o cidadão quase nunca percebe o tamanho do valor que está cedendo.</p><p>A expressão “novo petróleo” ajuda a entender o valor econômico dos dados, mas tem limite. Diferente do petróleo, dados podem ser copiados, combinados e reutilizados em múltiplas camadas. Quanto mais conectados a sistemas de IA, mais poderosos ficam. Eles não apenas descrevem o passado; ajudam a prever o futuro e a moldar decisões. Por isso a disputa por dados é também disputa por capacidade de orientar mercados, política, consumo e comportamento.</p><p>No longo prazo, a grande questão será esta: quem governa os dados que governam o mundo? Sem transparência, regulação séria e infraestrutura digital própria, países e cidadãos correm o risco de viver num ambiente em que a riqueza informacional é extraída constantemente sem retorno proporcional de autonomia. Dados não são apenas ativos econômicos. São peças centrais da liberdade contemporânea.</p>`
);
add(
  'Educação na Era das Máquinas: O que Ainda Vale Aprender?',
  'Education in the Age of Machines: What Is Still Worth Learning?',
  'Escreva um capítulo reflexivo sobre educação em um mundo de IA. Aborde memorização versus pensamento crítico, novas habilidades, criatividade, discernimento, adaptação profissional, risco de obsolescência curricular e a necessidade de formar humanos capazes de decidir em vez de apenas repetir.',
  `<h2>Educação na Era das Máquinas: O que Ainda Vale Aprender?</h2><p>Quando sistemas artificiais passam a responder perguntas, resumir textos, programar, traduzir, organizar informação e apoiar decisões em segundos, a educação é obrigada a se olhar no espelho. Durante muito tempo, grande parte da escola e da formação profissional foi construída para premiar memorização, repetição e execução de tarefas previsíveis. O problema é que justamente essas dimensões estão entre as mais facilmente assistidas ou substituídas por máquinas.</p><p>Isso não significa que aprender conteúdo deixou de importar. Significa que o valor do conteúdo isolado mudou. Em um mundo com acesso abundante a informação e apoio algorítmico crescente, ganha importância quem sabe interpretar, conectar, questionar, filtrar, contextualizar e decidir. A educação do futuro não pode ser treinada apenas para responder corretamente. Ela precisa treinar pessoas para formular boas perguntas, reconhecer limites de modelos, identificar vieses e sustentar julgamento em cenários ambíguos.</p><p>Também será necessário revisar o que entendemos por competência. Habilidades como comunicação clara, cooperação, curiosidade disciplinada, pensamento crítico, imaginação aplicada, responsabilidade ética e capacidade de adaptação deixam de ser complementos simpáticos e passam a ser centrais. O profissional valioso tende a não ser apenas quem domina uma ferramenta, mas quem compreende o sistema, lê o contexto e responde por consequências.</p><p>Outro risco é o da obsolescência curricular. Muitas estruturas educacionais continuam ensinando para um mundo que já está desaparecendo. Formam pessoas para seguir instruções, quando o mercado exige leitura crítica. Premiam respostas padronizadas, quando a vantagem competitiva passa pela integração criativa entre humano e máquina. Se a educação não mudar, ela pode deixar de proteger o futuro e passar a atrasá-lo.</p><p>No fim, talvez a pergunta mais honesta não seja “o que a IA vai ensinar?”, mas “o que a humanidade precisa preservar em si mesma enquanto usa IA para aprender mais rápido?”. A resposta não está em competir com máquinas naquilo em que elas escalam melhor. Está em formar gente com repertório, discernimento, caráter e responsabilidade para decidir o rumo do que será feito com esse poder.</p>`
);
add(
  'O Corpo como Plataforma: Saúde, Sensores e Vigilância Biológica',
  'The Body as a Platform: Health, Sensors and Biological Surveillance',
  'Escreva um capítulo denso sobre transformação do corpo em fonte contínua de dados. Aborde wearables, saúde preditiva, seguros, empregadores, privacidade biométrica, benefícios clínicos e riscos de transformar sinais vitais em instrumento de vigilância e classificação.',
  `<h2>O Corpo como Plataforma: Saúde, Sensores e Vigilância Biológica</h2><p>Relógios inteligentes, anéis, sensores, aplicativos de saúde, dispositivos de sono, monitoramento cardíaco, glicose contínua, exames conectados e plataformas de bem-estar estão transformando o corpo em uma fonte permanente de dados. Isso abre possibilidades impressionantes. Doenças podem ser percebidas mais cedo, padrões fisiológicos podem ser acompanhados em tempo real e decisões clínicas podem se tornar mais precisas. Para medicina preventiva, esse avanço é enorme.</p><p>Mas o corpo medido também é o corpo exposto. Quando sinais vitais passam a circular em plataformas privadas, surge uma pergunta delicada: quem tem direito de saber tanto sobre você? Dados biométricos e fisiológicos são muito mais íntimos do que preferências de consumo. Eles revelam fragilidade, tendência, risco, rotina, estresse, sono, hábitos e padrões que podem ser usados para cuidado, mas também para classificação.</p><p>Imagine seguradoras ajustando preço em função do seu estilo biológico de vida. Imagine empregadores interessados em monitorar fadiga, foco, produtividade e recuperação. Imagine plataformas de saúde vendendo previsões comportamentais com base em seus sinais corporais. A linha entre medicina personalizada e vigilância biológica pode se tornar perigosamente tênue.</p><p>Há também uma mudança simbólica importante. Quando tudo vira métrica, o corpo corre o risco de ser tratado apenas como sistema de desempenho. O sujeito passa a se ver como painel. Essa mentalidade pode ajudar em alguns contextos, mas também pode produzir ansiedade, culpa e relação instrumental demais com a própria vida orgânica.</p><p>O desafio do futuro não será escolher entre medir e não medir. Será decidir sob quais regras medir, quem controla esses dados, como evitar abuso e como preservar dignidade num ambiente em que até o batimento cardíaco pode se tornar variável econômica. A promessa da saúde conectada é forte. Justamente por isso, os limites precisam ser ainda mais claros.</p>`
);
tema.estrutura.totalItens = caps.length;
fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
const confirm = JSON.parse(fs.readFileSync(path, 'utf8')).find(t => t.id === 2);
console.log(JSON.stringify({id: confirm.id, totalItens: confirm.estrutura.totalItens, capitulos: confirm.estrutura.capitulos.length, ultimo: confirm.estrutura.capitulos[confirm.estrutura.capitulos.length-1][0]}));
