from pathlib import Path

BASE = Path(r"C:\Users\Geovane TI\Documents\english-platform")

def read_text(path):
    for enc in ("utf-8", "cp1252", "latin-1"):
        try:
            return Path(path).read_text(encoding=enc)
        except Exception:
            pass
    raise RuntimeError(f"Cannot read {path}")

def write_text(path, text):
    Path(path).write_text(text, encoding="utf-8", newline="\n")

# db.js
path = BASE / "server" / "db.js"
text = read_text(path)
text = text.replace(
"""  `CREATE TABLE IF NOT EXISTS english_users (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    email TEXT NOT NULL UNIQUE,\n    password_hash TEXT,\n    auth_source TEXT NOT NULL DEFAULT 'local',\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n  )`,\n""",
"""  `CREATE TABLE IF NOT EXISTS english_users (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    email TEXT NOT NULL UNIQUE,\n    password_hash TEXT,\n    auth_source TEXT NOT NULL DEFAULT 'local',\n    role TEXT NOT NULL DEFAULT 'user',\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n  )`,\n""")
text = text.replace(
"""  `CREATE TABLE IF NOT EXISTS english_wiki_words (\n    rank_order INTEGER PRIMARY KEY,\n    word TEXT NOT NULL UNIQUE,\n    normalized_word TEXT NOT NULL,\n    source TEXT NOT NULL DEFAULT 'wiki-100k',\n    part_of_speech TEXT NOT NULL DEFAULT '',\n    meanings JSONB NOT NULL DEFAULT '[]'::jsonb,\n    examples JSONB NOT NULL DEFAULT '[]'::jsonb,\n    synonyms JSONB NOT NULL DEFAULT '[]'::jsonb,\n    ipa TEXT NOT NULL DEFAULT '',\n    audio_url TEXT NOT NULL DEFAULT '',\n    meanings_verified_count INTEGER NOT NULL DEFAULT 0,\n    meanings_verified_at TIMESTAMPTZ,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n  )`,\n""",
"""  `CREATE TABLE IF NOT EXISTS english_wiki_words (\n    rank_order INTEGER PRIMARY KEY,\n    word TEXT NOT NULL UNIQUE,\n    normalized_word TEXT NOT NULL,\n    source TEXT NOT NULL DEFAULT 'wiki-100k',\n    part_of_speech TEXT NOT NULL DEFAULT '',\n    meanings JSONB NOT NULL DEFAULT '[]'::jsonb,\n    examples JSONB NOT NULL DEFAULT '[]'::jsonb,\n    synonyms JSONB NOT NULL DEFAULT '[]'::jsonb,\n    ipa TEXT NOT NULL DEFAULT '',\n    audio_url TEXT NOT NULL DEFAULT '',\n    meanings_verified_count INTEGER NOT NULL DEFAULT 0,\n    meanings_verified_at TIMESTAMPTZ,\n    meanings_quality_score INTEGER NOT NULL DEFAULT 0,\n    meanings_status TEXT NOT NULL DEFAULT 'pending',\n    meanings_review_notes TEXT NOT NULL DEFAULT '',\n    meanings_last_source TEXT NOT NULL DEFAULT '',\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n  )`,\n""")
text = text.replace(
"""  await pool.query(\n    `ALTER TABLE english_wiki_words ADD COLUMN IF NOT EXISTS meanings_verified_at TIMESTAMPTZ`\n  );\n  await pool.query(\n    `ALTER TABLE english_ui_labels ADD COLUMN IF NOT EXISTS text_value TEXT NOT NULL DEFAULT ''`\n  );\n""",
"""  await pool.query(\n    `ALTER TABLE english_users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user'`\n  );\n  await pool.query(\n    `ALTER TABLE english_wiki_words ADD COLUMN IF NOT EXISTS meanings_verified_at TIMESTAMPTZ`\n  );\n  await pool.query(\n    `ALTER TABLE english_wiki_words ADD COLUMN IF NOT EXISTS meanings_quality_score INTEGER NOT NULL DEFAULT 0`\n  );\n  await pool.query(\n    `ALTER TABLE english_wiki_words ADD COLUMN IF NOT EXISTS meanings_status TEXT NOT NULL DEFAULT 'pending'`\n  );\n  await pool.query(\n    `ALTER TABLE english_wiki_words ADD COLUMN IF NOT EXISTS meanings_review_notes TEXT NOT NULL DEFAULT ''`\n  );\n  await pool.query(\n    `ALTER TABLE english_wiki_words ADD COLUMN IF NOT EXISTS meanings_last_source TEXT NOT NULL DEFAULT ''`\n  );\n  await pool.query(\n    `ALTER TABLE english_ui_labels ADD COLUMN IF NOT EXISTS text_value TEXT NOT NULL DEFAULT ''`\n  );\n""")
text = text.replace(
'    ["admin.dict.verified", "en-US", "Verified"],',
'    ["admin.dict.verified", "en-US", "Verified"],\n    ["admin.dict.status", "pt-BR", "Status de qualidade"],\n    ["admin.dict.status", "en-US", "Quality status"],\n    ["admin.dict.score", "pt-BR", "Score de qualidade"],\n    ["admin.dict.score", "en-US", "Quality score"],\n    ["admin.dict.notes", "pt-BR", "Notas de revisao"],\n    ["admin.dict.notes", "en-US", "Review notes"],\n    ["admin.denied", "pt-BR", "Acesso restrito a administradores."],\n    ["admin.denied", "en-US", "Access restricted to administrators."],\n    ["dashboard.admin_role", "pt-BR", "Admin"],\n    ["dashboard.admin_role", "en-US", "Admin"],'
)
write_text(path, text)

# server/index.js
path = BASE / "server" / "index.js"
text = read_text(path)
if 'const ADMIN_EMAILS' not in text:
    text = text.replace('const LOCAL_PROGRESS_PATH = path.resolve(SERVER_DIR, "..", "progress.json");\n', 'const LOCAL_PROGRESS_PATH = path.resolve(SERVER_DIR, "..", "progress.json");\nconst ADMIN_EMAILS = String(process.env.ADMIN_EMAILS || "").split(",").map((item) => item.trim().toLowerCase()).filter(Boolean);\n')
if 'function resolveUserRole' not in text:
    text = text.replace('function buildCookieOptions(extra = {}) {\n  return {\n    httpOnly: true,\n    sameSite: "lax",\n    secure: false,\n    path: "/",\n    ...extra,\n  };\n}\n', 'function buildCookieOptions(extra = {}) {\n  return {\n    httpOnly: true,\n    sameSite: "lax",\n    secure: false,\n    path: "/",\n    ...extra,\n  };\n}\n\nfunction resolveUserRole(email = "") {\n  const normalized = String(email || "").trim().toLowerCase();\n  return ADMIN_EMAILS.includes(normalized) ? "admin" : "user";\n}\n')
if 'function assessMeaningQuality' not in text:
    text = text.replace('function compareMeanings(stored = [], fresh = []) {\n  const storedKeys = new Set(extractMeaningKeys(stored));\n  const freshKeys = new Set(extractMeaningKeys(fresh));\n  if (storedKeys.size === 0 || freshKeys.size === 0) {\n    return { ok: false, ratio: 0 };\n  }\n\n  let intersection = 0;\n  for (const key of storedKeys) {\n    if (freshKeys.has(key)) intersection += 1;\n  }\n\n  const minSize = Math.min(storedKeys.size, freshKeys.size);\n  const ratio = minSize ? intersection / minSize : 0;\n  return { ok: ratio >= 0.45, ratio };\n}\n', 'function compareMeanings(stored = [], fresh = []) {\n  const storedKeys = new Set(extractMeaningKeys(stored));\n  const freshKeys = new Set(extractMeaningKeys(fresh));\n  if (storedKeys.size === 0 || freshKeys.size === 0) {\n    return { ok: false, ratio: 0 };\n  }\n\n  let intersection = 0;\n  for (const key of storedKeys) {\n    if (freshKeys.has(key)) intersection += 1;\n  }\n\n  const minSize = Math.min(storedKeys.size, freshKeys.size);\n  const ratio = minSize ? intersection / minSize : 0;\n  return { ok: ratio >= 0.45, ratio };\n}\n\nfunction assessMeaningQuality(word, meanings = []) {\n  const lowerWord = String(word || "").toLowerCase();\n  const items = Array.isArray(meanings) ? meanings : [];\n  if (!items.length) {\n    return { score: 0, status: "missing", notes: "No meanings saved yet." };\n  }\n\n  let score = Math.min(30, items.length * 8);\n  const combined = items.map((item) => `${item?.partOfSpeech || ""} ${item?.english || ""}`).join(" ").toLowerCase();\n\n  if (combined.includes("language")) score += 18;\n  if (combined.includes("england") || combined.includes("english language")) score += 10;\n  if (lowerWord === "english" && (combined.includes("spin") || combined.includes("billiards") || combined.includes("bowling"))) score -= 35;\n  if (["their", "theirs"].includes(lowerWord) && combined.includes("belonging to or associated with them")) score += 20;\n  if (combined.includes(lowerWord)) score += 5;\n\n  const finalScore = Math.max(0, Math.min(100, score));\n  const status = finalScore >= 75 ? "verified" : finalScore >= 45 ? "needs_review" : "weak";\n  const notes = status === "verified"\n    ? "Meanings look consistent with the current checks."\n    : status === "needs_review"\n      ? "Meanings are usable but should be reviewed again."\n      : "Meanings look weak or suspicious for this word.";\n\n  return { score: finalScore, status, notes };\n}\n')
text = text.replace('`INSERT INTO english_users (id, name, email, password_hash, auth_source)\n     VALUES ($1, $2, $3, $4, $5)`', '`INSERT INTO english_users (id, name, email, password_hash, auth_source, role)\n     VALUES ($1, $2, $3, $4, $5, $6)`')
text = text.replace('[userId, name, email.toLowerCase(), passwordHash, authSource]', '[userId, name, email.toLowerCase(), passwordHash, authSource, resolveUserRole(email)]')
text = text.replace('SELECT u.id, u.name, u.email, u.password_hash, u.auth_source, s.plan, s.status,', 'SELECT u.id, u.name, u.email, u.password_hash, u.auth_source, u.role, s.plan, s.status,')
text = text.replace('SELECT s.id AS session_id, s.user_id, s.expires_at, u.name, u.email, u.auth_source,', 'SELECT s.id AS session_id, s.user_id, s.expires_at, u.name, u.email, u.auth_source, u.role,')
text = text.replace('      auth_source: session.auth_source,', '      auth_source: session.auth_source,\n      role: session.role || "user",')
text = text.replace('      auth_source: user.auth_source,', '      auth_source: user.auth_source,\n      role: user.role || "user",')
if 'function requireAdmin' not in text:
    text = text.replace('function requireAuth(handler) {\n  return async (req, res) => {\n    try {\n      const auth = await getCurrentAuth(req);\n      if (!auth) {\n        res.status(401).json({ error: "Sessao invalida ou expirada." });\n        return;\n      }\n      req.auth = auth;\n      await handler(req, res);\n    } catch (error) {\n      res.status(500).json({ error: "Falha de autenticacao.", detail: error.message });\n    }\n  };\n}\n', 'function requireAuth(handler) {\n  return async (req, res) => {\n    try {\n      const auth = await getCurrentAuth(req);\n      if (!auth) {\n        res.status(401).json({ error: "Sessao invalida ou expirada." });\n        return;\n      }\n      req.auth = auth;\n      await handler(req, res);\n    } catch (error) {\n      res.status(500).json({ error: "Falha de autenticacao.", detail: error.message });\n    }\n  };\n}\n\nfunction requireAdmin(handler) {\n  return requireAuth(async (req, res) => {\n    if (String(req.auth?.user?.role || "user") !== "admin") {\n      res.status(403).json({ error: "Acesso restrito a administradores." });\n      return;\n    }\n    await handler(req, res);\n  });\n}\n')
text = text.replace('app.get("/api/admin/dictionary/entries", requireAuth(async (req, res) => {', 'app.get("/api/admin/me", requireAuth(async (req, res) => {\n  res.json({ role: req.auth.user.role || "user", is_admin: String(req.auth.user.role || "user") === "admin" });\n}));\n\napp.get("/api/admin/dictionary/entries", requireAdmin(async (req, res) => {')
text = text.replace('app.patch("/api/admin/dictionary/entries/:word", requireAuth(async (req, res) => {', 'app.patch("/api/admin/dictionary/entries/:word", requireAdmin(async (req, res) => {')
text = text.replace('app.post("/api/admin/dictionary/reverify/:word", requireAuth(async (req, res) => {', 'app.post("/api/admin/dictionary/reverify/:word", requireAdmin(async (req, res) => {')
text = text.replace('app.get("/api/admin/i18n/labels", requireAuth(async (req, res) => {', 'app.get("/api/admin/i18n/labels", requireAdmin(async (req, res) => {')
text = text.replace('app.patch("/api/admin/i18n/labels/:labelKey", requireAuth(async (req, res) => {', 'app.patch("/api/admin/i18n/labels/:labelKey", requireAdmin(async (req, res) => {')
text = text.replace('SELECT word, normalized_word, part_of_speech, meanings, examples, synonyms, ipa, audio_url,\n              meanings_verified_count, meanings_verified_at', 'SELECT word, normalized_word, part_of_speech, meanings, examples, synonyms, ipa, audio_url,\n              meanings_verified_count, meanings_verified_at, meanings_quality_score, meanings_status, meanings_review_notes, meanings_last_source')
text = text.replace('SELECT word, normalized_word, part_of_speech, meanings, examples, synonyms, ipa, audio_url,\n            meanings_verified_count, meanings_verified_at', 'SELECT word, normalized_word, part_of_speech, meanings, examples, synonyms, ipa, audio_url,\n            meanings_verified_count, meanings_verified_at, meanings_quality_score, meanings_status, meanings_review_notes, meanings_last_source')
# patch verifier update SQLs
text = text.replace('const comparison = compareMeanings(storedMeanings, apiData.meanings);\n      if (!comparison.ok) {', 'const comparison = compareMeanings(storedMeanings, apiData.meanings);\n      const quality = assessMeaningQuality(word, apiData.meanings);\n      if (!comparison.ok) {')
text = text.replace('               ipa = $6,\n               audio_url = $7,\n               meanings_verified_count = meanings_verified_count + 1,\n               meanings_verified_at = NOW()\n           WHERE normalized_word = $1`', '               ipa = $6,\n               audio_url = $7,\n               meanings_quality_score = $8,\n               meanings_status = $9,\n               meanings_review_notes = $10,\n               meanings_last_source = $11,\n               meanings_verified_count = meanings_verified_count + 1,\n               meanings_verified_at = NOW()\n           WHERE normalized_word = $1`')
text = text.replace('            apiData.ipa || "",\n            apiData.audioUrl || "",\n          ]', '            apiData.ipa || "",\n            apiData.audioUrl || "",\n            quality.score,\n            quality.status,\n            quality.notes,\n            "dictionaryapi.dev",\n          ]')
text = text.replace('           SET meanings_verified_count = meanings_verified_count + 1,\n               meanings_verified_at = NOW()\n           WHERE normalized_word = $1`', '           SET meanings_quality_score = $2,\n               meanings_status = $3,\n               meanings_review_notes = $4,\n               meanings_last_source = $5,\n               meanings_verified_count = meanings_verified_count + 1,\n               meanings_verified_at = NOW()\n           WHERE normalized_word = $1`')
text = text.replace('[normalized]\n        );', '[normalized, quality.score, quality.status, quality.notes, "dictionaryapi.dev"]\n        );', 1)
# patch dictionary GET update query
text = text.replace('               ipa = $6,\n               audio_url = $7\n           WHERE normalized_word = $1`', '               ipa = $6,\n               audio_url = $7,\n               meanings_quality_score = $8,\n               meanings_status = $9,\n               meanings_review_notes = $10,\n               meanings_last_source = $11\n           WHERE normalized_word = $1`')
text = text.replace('        await pool.query(\n          `UPDATE english_wiki_words\n           SET part_of_speech = $2,\n               meanings = $3::jsonb,\n               examples = $4::jsonb,\n               synonyms = $5::jsonb,\n               ipa = $6,\n               audio_url = $7,\n               meanings_quality_score = $8,\n               meanings_status = $9,\n               meanings_review_notes = $10,\n               meanings_last_source = $11\n           WHERE normalized_word = $1`,\n          [\n            normalized,\n            apiData.partOfSpeech || "",\n            JSON.stringify(meanings),\n            JSON.stringify(examples),\n            JSON.stringify(synonyms),\n            apiData.ipa || "",\n            apiData.audioUrl || "",\n          ]\n        );', '        const quality = assessMeaningQuality(rawWord, meanings);\n        await pool.query(\n          `UPDATE english_wiki_words\n           SET part_of_speech = $2,\n               meanings = $3::jsonb,\n               examples = $4::jsonb,\n               synonyms = $5::jsonb,\n               ipa = $6,\n               audio_url = $7,\n               meanings_quality_score = $8,\n               meanings_status = $9,\n               meanings_review_notes = $10,\n               meanings_last_source = $11\n           WHERE normalized_word = $1`,\n          [\n            normalized,\n            apiData.partOfSpeech || "",\n            JSON.stringify(meanings),\n            JSON.stringify(examples),\n            JSON.stringify(synonyms),\n            apiData.ipa || "",\n            apiData.audioUrl || "",\n            quality.score,\n            quality.status,\n            quality.notes,\n            "dictionaryapi.dev",\n          ]\n        );')
# patch admin save query
text = text.replace('           ipa = $6,\n           audio_url = $7\n       WHERE normalized_word = $1`', '           ipa = $6,\n           audio_url = $7,\n           meanings_quality_score = $8,\n           meanings_status = $9,\n           meanings_review_notes = $10,\n           meanings_last_source = $11\n       WHERE normalized_word = $1`')
text = text.replace('[normalized, partOfSpeech, JSON.stringify(meanings), JSON.stringify(examples), JSON.stringify(synonyms), ipa, audioUrl]', '[normalized, partOfSpeech, JSON.stringify(meanings), JSON.stringify(examples), JSON.stringify(synonyms), ipa, audioUrl, assessMeaningQuality(rawWord, meanings).score, assessMeaningQuality(rawWord, meanings).status, assessMeaningQuality(rawWord, meanings).notes, "admin_manual"]')
# patch admin reverify query
text = text.replace('           ipa = $6,\n           audio_url = $7,\n           meanings_verified_count = meanings_verified_count + 1,\n           meanings_verified_at = NOW()\n       WHERE normalized_word = $1`', '           ipa = $6,\n           audio_url = $7,\n           meanings_quality_score = $8,\n           meanings_status = $9,\n           meanings_review_notes = $10,\n           meanings_last_source = $11,\n           meanings_verified_count = meanings_verified_count + 1,\n           meanings_verified_at = NOW()\n       WHERE normalized_word = $1`')
text = text.replace('    await pool.query(\n      `UPDATE english_wiki_words\n       SET part_of_speech = $2,\n           meanings = $3::jsonb,\n           examples = $4::jsonb,\n           synonyms = $5::jsonb,\n           ipa = $6,\n           audio_url = $7,\n           meanings_quality_score = $8,\n           meanings_status = $9,\n           meanings_review_notes = $10,\n           meanings_last_source = $11,\n           meanings_verified_count = meanings_verified_count + 1,\n           meanings_verified_at = NOW()\n       WHERE normalized_word = $1`,\n      [\n        normalized,\n        apiData.partOfSpeech || "",\n        JSON.stringify(apiData.meanings || []),\n        JSON.stringify(apiData.examples || []),\n        JSON.stringify(apiData.synonyms || []),\n        apiData.ipa || "",\n        apiData.audioUrl || "",\n      ]\n    );', '    const quality = assessMeaningQuality(rawWord, apiData.meanings || []);\n    await pool.query(\n      `UPDATE english_wiki_words\n       SET part_of_speech = $2,\n           meanings = $3::jsonb,\n           examples = $4::jsonb,\n           synonyms = $5::jsonb,\n           ipa = $6,\n           audio_url = $7,\n           meanings_quality_score = $8,\n           meanings_status = $9,\n           meanings_review_notes = $10,\n           meanings_last_source = $11,\n           meanings_verified_count = meanings_verified_count + 1,\n           meanings_verified_at = NOW()\n       WHERE normalized_word = $1`,\n      [\n        normalized,\n        apiData.partOfSpeech || "",\n        JSON.stringify(apiData.meanings || []),\n        JSON.stringify(apiData.examples || []),\n        JSON.stringify(apiData.synonyms || []),\n        apiData.ipa || "",\n        apiData.audioUrl || "",\n        quality.score,\n        quality.status,\n        quality.notes,\n        "dictionaryapi.dev",\n      ]\n    );')
write_text(path, text)

# Initial.jsx
path = BASE / "src" / "components" / "Initial.jsx"
text = read_text(path)
if 'const isAdminUser' not in text:
    text = text.replace('  const isPremiumUser = String(authUser?.subscription?.plan || "free").toLowerCase() === "premium";\n', '  const isPremiumUser = String(authUser?.subscription?.plan || "free").toLowerCase() === "premium";\n  const isAdminUser = String(authUser?.role || "user").toLowerCase() === "admin";\n')
text = text.replace('  if (activeScreen === "admin") {\n    return (\n      <ContentAdmin\n        onBack={() => setActiveScreen("home")}\n        color="#4b7bec"\n      />\n    );\n  }\n', '  if (activeScreen === "admin") {\n    if (!isAdminUser) {\n      setActiveScreen("home");\n      return null;\n    }\n    return (\n      <ContentAdmin\n        onBack={() => setActiveScreen("home")}\n        color="#4b7bec"\n      />\n    );\n  }\n')
text = text.replace('        <div className="duo-info-card">\n          <div className="duo-info-head">\n            <span>{getUiLabel("menu.content_admin", "Content admin")}</span>\n            <button type="button" onClick={() => setActiveScreen("admin")}>CMS</button>\n          </div>\n          <p className="duo-onboarding-copy">{getUiLabel("dashboard.admin_copy", "Edit app labels and review dictionary entries from one internal panel.")}</p>\n          <div className="duo-report-actions">\n            <button type="button" onClick={() => setActiveScreen("admin")}>\n              <NotebookPen size={14} />\n              {getUiLabel("dashboard.open_admin", "Open admin")}\n            </button>\n            <button type="button" className="is-secondary" onClick={() => openModuleByKey("community")}>\n              <Users size={14} />\n              {getUiLabel("module.community", "Community")}\n            </button>\n          </div>\n        </div>\n\n', '        {isAdminUser ? (\n        <div className="duo-info-card">\n          <div className="duo-info-head">\n            <span>{getUiLabel("menu.content_admin", "Content admin")}</span>\n            <button type="button" onClick={() => setActiveScreen("admin")}>{getUiLabel("dashboard.admin_role", "Admin")}</button>\n          </div>\n          <p className="duo-onboarding-copy">{getUiLabel("dashboard.admin_copy", "Edit app labels and review dictionary entries from one internal panel.")}</p>\n          <div className="duo-report-actions">\n            <button type="button" onClick={() => setActiveScreen("admin")}>\n              <NotebookPen size={14} />\n              {getUiLabel("dashboard.open_admin", "Open admin")}\n            </button>\n            <button type="button" className="is-secondary" onClick={() => openModuleByKey("community")}>\n              <Users size={14} />\n              {getUiLabel("module.community", "Community")}\n            </button>\n          </div>\n        </div>\n        ) : null}\n\n')
write_text(path, text)

# ContentAdmin.jsx add fields
path = BASE / "src" / "components" / "ContentAdmin.jsx"
text = read_text(path)
text = text.replace('                  <label>\n                    <div style={{ marginBottom: 6 }}>{getUiLabel("admin.dict.verified", "Verified")}</div>\n                    <input value={`${dictionaryForm.meanings_verified_count || 0}${dictionaryForm.meanings_verified_at ? ` | ${dictionaryForm.meanings_verified_at}` : ""}`} readOnly style={{ width: "100%", background: "#0d2433", color: "#9fb4c4", border: "1px solid #31546c", borderRadius: 14, padding: "12px 14px" }} />\n                  </label>\n', '                  <label>\n                    <div style={{ marginBottom: 6 }}>{getUiLabel("admin.dict.verified", "Verified")}</div>\n                    <input value={`${dictionaryForm.meanings_verified_count || 0}${dictionaryForm.meanings_verified_at ? ` | ${dictionaryForm.meanings_verified_at}` : ""}`} readOnly style={{ width: "100%", background: "#0d2433", color: "#9fb4c4", border: "1px solid #31546c", borderRadius: 14, padding: "12px 14px" }} />\n                  </label>\n                </div>\n                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>\n                  <label>\n                    <div style={{ marginBottom: 6 }}>{getUiLabel("admin.dict.status", "Quality status")}</div>\n                    <input value={dictionaryForm.meanings_status || "pending"} readOnly style={{ width: "100%", background: "#0d2433", color: "#9fb4c4", border: "1px solid #31546c", borderRadius: 14, padding: "12px 14px" }} />\n                  </label>\n                  <label>\n                    <div style={{ marginBottom: 6 }}>{getUiLabel("admin.dict.score", "Quality score")}</div>\n                    <input value={String(dictionaryForm.meanings_quality_score || 0)} readOnly style={{ width: "100%", background: "#0d2433", color: "#9fb4c4", border: "1px solid #31546c", borderRadius: 14, padding: "12px 14px" }} />\n                  </label>\n                </div>\n                <label>\n                  <div style={{ marginBottom: 6 }}>{getUiLabel("admin.dict.notes", "Review notes")}</div>\n                  <textarea rows={3} value={dictionaryForm.meanings_review_notes || ""} readOnly style={{ width: "100%", background: "#0d2433", color: "#9fb4c4", border: "1px solid #31546c", borderRadius: 14, padding: "12px 14px" }} />\n                </label>\n                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>\n')
write_text(path, text)

# checklist
path = BASE / "checklist-english-platform.md"
text = read_text(path)
if '- [x] Regras premium/backend mais completas' not in text:
    text += '\n- [x] Regras de admin/roles aplicadas no backend e no painel interno\n- [x] Dictionary com status, score e notas de qualidade para meanings\n'
write_text(path, text)
