const fs = require('fs');
const path = 'C:/Users/Geovane TI/Documents/automatizador-pdf/temas.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));
const tema = data.find(t => t.id === 2);
if (!tema) throw new Error('ID 2 não encontrado');
tema.feito = false;
tema.estrutura.totalItens = 6;
const chapters = [];
function chapter(pt, en, prompt, html){ chapters.push([pt, en, false, prompt, html]); }
chapter(
  'Biohacking: O Upgrade do Corpo Humano',
  'Biohacking: The Upgrade of the Human Body',
  'Escreva um capítulo profundo e acessível sobre biohacking, explicando como pessoas comuns e profissionais de alta performance tentam otimizar corpo e mente por meio de sono, nutrição, treino, luz, suplementação, monitoramento de dados, controle do estresse e hábitos consistentes. Mostre os benefícios reais, os exageros do mercado, os riscos de atalhos e a diferença entre autocuidado inteligente e obsessão por performance.',
  `<h2>Biohacking: O Upgrade do Corpo Humano</h2><p>Biohacking é a tentativa de melhorar o funcionamento do corpo e da mente com decisões mais conscientes. Em vez de viver no piloto automático, a pessoa começa a observar sono, energia, alimentação, foco, treino, humor e recuperação para entender o que está ajudando e o que está sabotando sua rotina. O conceito parece moderno, mas no fundo ele parte de uma pergunta antiga: como extrair o melhor do próprio organismo sem se destruir no processo?</p><p>O lado saudável do biohacking começa no básico. Dormir melhor, respeitar o ritmo biológico, se expor à luz natural pela manhã, reduzir excesso de tela à noite, organizar horários de refeição, consumir proteína suficiente, treinar de forma consistente e criar momentos reais de descanso. Quando essa base melhora, quase tudo melhora junto: clareza mental, disposição, humor, imunidade e capacidade de recuperação.</p><p>O problema aparece quando o biohacking vira espetáculo. A internet transformou hábitos simples em performance estética. De repente, muita gente acha que só terá resultado se comprar um relógio caro, um suplemento exótico, um protocolo radical ou uma rotina impraticável. Só que tecnologia sem fundamento raramente resolve. Quem dorme mal, come mal e vive hiperestimulado não será salvo por um gadget.</p><p>Também existe o risco da obsessão. Medir dados pode ser útil, mas nem todo número merece dominar sua vida. Quando a pessoa perde a capacidade de sentir o próprio corpo e passa a consultar apenas um aplicativo, o cuidado já está ficando distorcido. Saúde não pode depender de ansiedade por otimização.</p><p>O biohacking mais inteligente não busca perfeição. Ele busca previsibilidade, energia sustentável e autoconsciência. O verdadeiro upgrade humano não está em virar uma máquina. Está em entender melhor a própria biologia para viver com mais lucidez, menos sabotagem e mais constância.</p>`
);

chapter(
  'A Singularidade: O Ponto de Não Retorno',
  'The Singularity: The Point of No Return',
  'Escreva um capítulo denso, claro e instigante sobre a singularidade tecnológica. Explique o conceito de um ponto em que a inteligência artificial e a capacidade computacional evoluem tão rapidamente que o futuro se torna imprevisível para os humanos. Aborde cenários otimistas e pessimistas, concentração de poder, alinhamento de IA, risco existencial, aceleração tecnológica e impactos sociais.',
  `<h2>A Singularidade: O Ponto de Não Retorno</h2><p>A singularidade tecnológica é a hipótese de que chegaremos a um momento em que sistemas artificiais se tornarão tão poderosos e tão capazes de acelerar a própria evolução que o futuro passará a escapar da compreensão humana comum. Não se trata apenas de máquinas mais rápidas. Trata-se de um possível salto de inteligência e automação em que nossas referências atuais deixariam de ser suficientes.</p><p>Para quem olha com otimismo, a singularidade pode significar cura acelerada de doenças, novos materiais, avanços energéticos, ciência mais rápida e soluções inéditas para problemas históricos. Uma inteligência supercapaz poderia ampliar enormemente a capacidade humana de descobrir, organizar e construir.</p><p>Mas existe o outro lado. Quanto mais poder tecnológico é concentrado, maior o risco de desigualdade, manipulação, dependência e perda de autonomia. Uma IA extremamente poderosa não precisa ser maldosa para ser perigosa. Basta perseguir objetivos mal definidos, operar em sistemas sem supervisão real ou ficar nas mãos de agentes movidos por interesses estreitos.</p><p>O debate sobre singularidade também revela uma fragilidade do nosso tempo: a inovação corre muito mais rápido do que a governança. Empresas lançam tecnologias em semanas; leis e acordos levam anos. Esse descompasso cria um ambiente em que grandes transformações podem se consolidar antes mesmo de a sociedade entender o que está aceitando.</p><p>No fundo, a singularidade é menos sobre ficção e mais sobre responsabilidade. A grande pergunta não é só se conseguiremos criar sistemas extraordinários. A pergunta decisiva é se teremos maturidade política, moral e institucional para conviver com eles sem entregar o futuro a uma lógica que ninguém mais consegue controlar.</p>`
);
chapter(
  'Cidades Inteligentes e o Controle Total',
  'Smart Cities and Total Control',
  'Escreva um capítulo reflexivo sobre cidades inteligentes, mostrando os benefícios de sensores, automação urbana, mobilidade conectada, serviços públicos integrados e análise de dados em tempo real. Ao mesmo tempo, explore os riscos de vigilância permanente, pontuação social, perda de privacidade, discriminação algorítmica e dependência tecnológica.',
  `<h2>Cidades Inteligentes e o Controle Total</h2><p>A cidade inteligente promete resolver antigos problemas urbanos com dados, sensores e automação. Trânsito mais eficiente, energia melhor distribuída, coleta de lixo otimizada, monitoramento ambiental em tempo real, serviços públicos digitais e respostas mais rápidas a emergências. Sob esse ponto de vista, usar tecnologia para fazer a cidade funcionar melhor parece uma escolha óbvia.</p><p>De fato, há ganhos importantes. Quando o transporte se adapta ao fluxo real, quando a iluminação responde ao uso, quando redes detectam falhas antes do colapso e quando a gestão urbana passa a agir com precisão em vez de improviso, a vida coletiva melhora. Em um mundo mais populoso e pressionado por crise climática, inteligência urbana pode significar eficiência, economia e menos desperdício.</p><p>O problema é que toda cidade inteligente também é uma cidade que observa. Para reagir em tempo real, ela coleta informação em tempo real. Câmeras, placas, deslocamentos, dispositivos, padrões de consumo e comportamento deixam rastros. A linha entre gestão eficiente e vigilância permanente pode ficar perigosamente fina.</p><p>Privacidade urbana não é capricho. Ela protege autonomia, dignidade e liberdade civil. Se cada deslocamento, hábito ou presença puder ser correlacionado em sistemas opacos, abre-se espaço para discriminação algorítmica, policiamento enviesado e controle silencioso. Mesmo sem um sistema explícito de pontuação social, decisões automatizadas já podem privilegiar uns e dificultar a vida de outros.</p><p>O desafio real não é rejeitar a cidade inteligente, mas impedir que eficiência vire justificativa para poder sem freio. Tecnologia urbana precisa de limites claros, auditoria, transparência e proteção efetiva aos cidadãos. Uma cidade boa não é só a que funciona melhor. É a que melhora a vida sem transformar seus habitantes em objetos permanentes de rastreamento.</p>`
);

chapter(
  'O Fim do Trabalho: A Era da Automação Total',
  'The End of Work: The Era of Total Automation',
  'Escreva um capítulo humano e analítico sobre automação total. Aborde substituição de tarefas humanas por IA e robótica, impacto em empregos administrativos, industriais e criativos, novas profissões, necessidade de requalificação, renda, desigualdade e identidade ligada ao trabalho.',
  `<h2>O Fim do Trabalho: A Era da Automação Total</h2><p>Automação sempre existiu, mas agora ela começa a atingir não apenas tarefas manuais e repetitivas. Sistemas de IA, robótica e software avançado já são capazes de executar partes importantes do trabalho administrativo, industrial, criativo e analítico. Isso muda o debate: não se trata mais apenas de substituir força física, e sim de reorganizar o valor do trabalho humano em larga escala.</p><p>O primeiro impacto aparece nas tarefas, não necessariamente nos cargos inteiros. Uma profissão pode continuar existindo, mas perder boa parte das atividades que justificavam seu preço de mercado. Um redator passa a disputar espaço com geração automática de texto. Um analista vê relatórios sendo produzidos por sistemas. Um atendente é substituído por fluxos automatizados. Pouco a pouco, a máquina não elimina só empregos. Ela corrói o valor percebido de certas funções.</p><p>É verdade que novas ocupações surgem. A história da tecnologia mostra isso. Mas a transição não é neutra. Nem toda pessoa consegue se requalificar no ritmo exigido. Nem todo novo trabalho absorve o mesmo volume de gente. E nem todo ganho de produtividade é distribuído de forma justa. Sem políticas de transição, requalificação séria e novos modelos de proteção social, a automação pode ampliar desigualdade em vez de produzir liberdade.</p><p>Existe ainda uma camada psicológica. O trabalho também organiza identidade, rotina, pertencimento e senso de utilidade. Quando uma tecnologia reduz a necessidade de determinadas competências humanas, ela afeta não apenas renda, mas autoestima e significado. Esse é um ponto que discursos simplistas sobre inovação costumam ignorar.</p><p>O futuro do trabalho não será decidido só por máquinas. Ele será decidido por escolhas sociais: quem fica com os ganhos, quem financia a transição, como educamos pessoas para novas funções e que tipo de dignidade queremos preservar numa economia cada vez mais automatizada.</p>`
);
chapter(
  'Transumanismo: A Busca pela Imortalidade Digital',
  'The Search for Digital Immortality',
  'Escreva um capítulo filosófico e prático sobre transumanismo, explicando a tentativa de expandir as capacidades humanas com tecnologia, prolongar a vida, integrar cérebro e máquina e até imaginar consciência digital. Aborde próteses, interfaces neurais, upload mental, extensão radical da vida, limites biológicos, desigualdade de acesso e dilemas éticos.',
  `<h2>Transumanismo: A Busca pela Imortalidade Digital</h2><p>O transumanismo parte de uma ideia ousada: se a tecnologia já corrige limitações humanas, por que não deveria também ampliá-las? A partir dessa lógica surgem projetos de próteses avançadas, interfaces cérebro-máquina, extensão radical da vida, melhoria cognitiva e até a hipótese extrema de preservar a mente em ambientes digitais.</p><p>Uma parte desse movimento já é realidade em contextos médicos. Implantes, terapias genéticas, dispositivos neurais e próteses sofisticadas podem devolver autonomia e qualidade de vida. O debate muda de tom quando a tecnologia deixa de restaurar e passa a prometer aprimorar. Nesse ponto, não estamos mais apenas tratando fragilidades. Estamos redesenhando o que consideramos um ser humano “normal”.</p><p>A busca pela imortalidade digital leva a discussão ao limite. Se um dia for possível mapear com altíssima fidelidade a atividade mental, isso significaria transferência da consciência ou apenas a criação de uma cópia funcional? A pergunta parece filosófica, mas é central. Talvez possamos replicar memória e linguagem sem preservar a experiência subjetiva que dá continuidade real ao eu.</p><p>Também existe o problema da desigualdade. Tecnologias de aprimoramento radical dificilmente chegarão primeiro aos mais vulneráveis. Se alguns grupos puderem viver mais, pensar melhor ou se integrar mais profundamente às máquinas, o transumanismo corre o risco de produzir uma nova estratificação histórica: humanos ampliados e humanos comuns ocupando posições muito diferentes no mundo.</p><p>No seu melhor, o transumanismo expressa o desejo legítimo de reduzir sofrimento e ampliar autonomia. No seu pior, revela impaciência com a vulnerabilidade e fascínio por controle absoluto. Por isso ele importa tanto: porque nos obriga a decidir se queremos usar tecnologia para cuidar melhor da vida ou para fugir dela a qualquer custo.</p>`
);

chapter(
  'Ética no Novo Mundo: Quem Define as Regras?',
  'Ethics in the New World: Who Defines the Rules?',
  false,
  'Escreva um capítulo forte sobre ética no novo mundo tecnológico. Aborde governança de IA, responsabilidade por danos, privacidade, consentimento, desigualdade de acesso, manipulação algorítmica, bioética, regulação e conflito entre inovação rápida e proteção social.',
  `<h2>Ética no Novo Mundo: Quem Define as Regras?</h2><p>Toda tecnologia poderosa força a mesma pergunta: só porque podemos fazer algo, significa que devemos fazer? No mundo atual, essa pergunta deixou de ser filosófica no sentido distante e passou a ser operacional. Inteligência artificial, automação, biotecnologia, vigilância digital e sistemas preditivos já influenciam crédito, trabalho, saúde, consumo, mobilidade e segurança. Quando isso acontece, ética deixa de ser detalhe e passa a ser infraestrutura de proteção humana.</p><p>O ponto central não é apenas o que a tecnologia consegue fazer, mas quem define seus limites. Algoritmos são treinados por empresas, usados por governos, aplicados em mercados desiguais e consumidos por pessoas que quase nunca entendem plenamente seus mecanismos. Se a governança fica concentrada, o futuro também fica.</p><p>Responsabilidade é outro ponto crítico. Em sistemas complexos, danos costumam se diluir. Quando uma decisão automatizada discrimina, erra ou prejudica alguém, quem responde? O fornecedor? A instituição que aplicou? O gestor que aprovou? Sem resposta clara, a vítima fica exposta e o sistema continua operando como se o erro fosse apenas um detalhe técnico.</p><p>Há também o problema do consentimento. Em ambientes digitais, muita coleta de dados é tratada como escolha livre, mas quase sempre a liberdade é limitada. As pessoas aceitam termos opacos para continuar vivendo funcionalmente no mundo conectado. Isso permite que dados deixem de ser apenas informação e se tornem matéria-prima para influência, previsão e manipulação comportamental.</p><p>Ética no novo mundo significa reconhecer que inovação sem limite pode ampliar eficiência e, ao mesmo tempo, ampliar injustiça. Por isso regulação séria, auditoria, transparência e participação pública não são inimigas do progresso. São a única forma de impedir que o avanço técnico seja capturado por interesses estreitos e vendido como destino inevitável.</p>`
);

tema.estrutura.capitulos = chapters;
fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
const valid = JSON.parse(fs.readFileSync(path, 'utf8'));
const out = valid.find(t => t.id === 2);
console.log(JSON.stringify({ id: out.id, feito: out.feito, capitulos: out.estrutura.capitulos.length, cap0elementos: out.estrutura.capitulos[0].length, cap6titulo: out.estrutura.capitulos[5][0] }));

