function Apply-Replacements {
  param(
    [string]$Path,
    [array]$Pairs
  )

  $content = [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
  foreach ($pair in $Pairs) {
    $content = $content.Replace($pair.Old, $pair.New)
  }
  [System.IO.File]::WriteAllText($Path, $content, [System.Text.Encoding]::UTF8)
}

$grammarPath = "C:\Users\Geovane TI\Documents\english-platform\documentation\en\grammar-documentation.html"
$grammarPairs = @(
  @{ Old = "com foco em trilha pedagÃ³gica, tipos de exercÃ­cio, feedback adaptativo, persistence de progresso,"; New = "with a focus on the pedagogical path, exercise types, adaptive feedback, and progress persistence," },
  @{ Old = "O Grammar foi desenhado para funcionar como a espinha dorsal pedagÃ³gica da plataforma. Ele combina"; New = "Grammar was designed to work as the pedagogical backbone of the platform. It combines" },
  @{ Old = "trilha visual, practice progressiva, audio manual, fala, correction guiada e reforÃ§o adaptativo para"; New = "a visual path, progressive practice, manual audio, speaking, guided correction, and adaptive reinforcement to" },
  @{ Old = "transformar estudo gramatical em treino ativo."; New = "turn grammar study into active training." },
  @{ Old = "Trilha por levels"; New = "Level-based path" },
  @{ Old = "ExercÃ­cios variados"; New = "Varied exercises" },
  @{ Old = "Feedback pedagÃ³gico"; New = "Pedagogical feedback" },
  @{ Old = "IntegraÃ§Ã£o com Vocabulary"; New = "Vocabulary integration" },
  @{ Old = "seleÃ§Ã£o da translation ou estrutura correta."; New = "selection of the correct translation or structure." },
  @{ Old = "escuta com alternativas."; New = "listening with alternatives." },
  @{ Old = "escuta com velocidade controlada."; New = "listening with controlled speed." },
  @{ Old = "preenchimento de lacunas."; New = "gap filling." },
  @{ Old = "ditado com validaÃ§Ã£o textual."; New = "dictation with text validation." },
  @{ Old = "identificar e corrigir o trecho errado."; New = "identify and correct the wrong fragment." },
  @{ Old = "produÃ§Ã£o oral com score phonetic e de completude."; New = "oral production with phonetic and completeness scoring." },
  @{ Old = "<strong>1. Entrada na unidade</strong>"; New = "<strong>1. Unit entry</strong>" },
  @{ Old = "O aluno escolhe a unidade na trilha principal e vÃª a introduÃ§Ã£o do content atual."; New = "The learner chooses the unit on the main path and sees the introduction to the current content." },
  @{ Old = "<strong>2. Guia da unidade</strong>"; New = "<strong>2. Unit guide</strong>" },
  @{ Old = "Resumo do conceito, dicas rÃ¡pidas e objetivos da etapa."; New = "Concept summary, quick tips, and stage goals." },
  @{ Old = "<strong>3. ExecuÃ§Ã£o dos exercÃ­cios</strong>"; New = "<strong>3. Exercise execution</strong>" },
  @{ Old = "As questÃµes aparecem em sequÃªncia com progress bar, hearts e feedback compacto."; New = "Questions appear in sequence with a progress bar, hearts, and compact feedback." },
  @{ Old = "<strong>4. ReforÃ§o adaptativo</strong>"; New = "<strong>4. Adaptive reinforcement</strong>" },
  @{ Old = "QuestÃµes erradas podem voltar para o final da fila da mesma session."; New = "Wrong questions can return to the end of the queue in the same session." },
  @{ Old = "<strong>5. Fechamento</strong>"; New = "<strong>5. Wrap-up</strong>" },
  @{ Old = "Tela final com resultado, resumo e atualizaÃ§Ã£o do progresso da trilha."; New = "Final screen with results, summary, and a path progress update." },
  @{ Old = "<strong>Compacto:</strong> not cobre mais metade da tela."; New = "<strong>Compact:</strong> it no longer covers half of the screen." },
  @{ Old = "<strong>Contextual:</strong> explica a logic da resposta correta."; New = "<strong>Contextual:</strong> explains the logic behind the correct answer." },
  @{ Old = "<strong>Granular:</strong> separa erro gramatical, lexical, de ordem e phonetic."; New = "<strong>Granular:</strong> separates grammatical, lexical, word-order, and phonetic errors." },
  @{ Old = "<strong>Exemplo curto:</strong> reforÃ§a o conceito com aplicaÃ§Ã£o simples."; New = "<strong>Short example:</strong> reinforces the concept with a simple use case." },
  @{ Old = "<strong>Erro recorrente:</strong> falhas repetidas entram no caderno de erros."; New = "<strong>Recurring errors:</strong> repeated failures are added to the error notebook." },
  @{ Old = "conceitos frÃ¡geis podem alimentar a fila global de review."; New = "fragile concepts can feed the global review queue." },
  @{ Old = "<strong>Retomada:</strong> a session salva ponto de retorno e fila dynamic."; New = "<strong>Resume state:</strong> the session saves a return point and a dynamic queue." },
  @{ Old = "palavras relevantes e palavras de erro podem ser salvas no vocabulary."; New = "relevant words and error words can be saved to the vocabulary." },
  @{ Old = "patterns de erro sÃ£o registrados como comportamento recorrente."; New = "error patterns are recorded as recurring behavior." },
  @{ Old = "<strong>Profile e Reports:</strong> resultados podem alimentar view global do aluno."; New = "<strong>Profile and Reports:</strong> results can feed the learner's global view." },
  @{ Old = "Abaixo estÃ£o representaÃ§Ãµes visuais das principais telas do <strong>Grammar</strong>. Elas foram recriadas em HTML/CSS para documentar a experiÃªncia sem depender de prints estÃ¡ticos."; New = "Below are visual recreations of the main <strong>Grammar</strong> screens. They were rebuilt in HTML/CSS to document the experience without relying on static screenshots." },
  @{ Old = "<strong>1. Trilha principal</strong>"; New = "<strong>1. Main path</strong>" },
  @{ Old = "VisÃ£o do content atual e progressÃ£o na trilha."; New = "View of the current content and path progression." },
  @{ Old = '<div class="mock-node active">ðŸ‹</div>'; New = '<div class="mock-node active">Dumbbell</div>' },
  @{ Old = '<div class="mock-node">â˜…</div>'; New = '<div class="mock-node">Star</div>' },
  @{ Old = '<div class="mock-node">ðŸ“˜</div>'; New = '<div class="mock-node">Book</div>' },
  @{ Old = "<strong>2. ExercÃ­cio em andamento</strong>"; New = "<strong>2. Exercise in progress</strong>" },
  @{ Old = '<button class="mock-audio-btn" type="button">ðŸ”Š</button>'; New = '<button class="mock-audio-btn" type="button">Audio</button>' },
  @{ Old = 'Selecione a translation correta para "Good morning".'; New = 'Select the correct translation for "Good morning".' },
  @{ Old = 'Boa noite'; New = 'Good evening' },
  @{ Old = 'Bom dia'; New = 'Good morning' },
  @{ Old = 'Boa tarde'; New = 'Good afternoon' },
  @{ Old = '<strong>3. Feedback pedagÃ³gico</strong>'; New = '<strong>3. Pedagogical feedback</strong>' },
  @{ Old = 'CorreÃ§Ã£o compacta com explanation e continuidade.'; New = 'Compact correction with explanation and continuation.' },
  @{ Old = '<strong>Boa resposta</strong>'; New = '<strong>Correct answer</strong>' },
  @{ Old = 'Good morning corresponde ao cumprimento usado pela morning.'; New = 'Good morning matches the greeting used in the morning.' },
  @{ Old = 'Conceito: Greetings Time Of Day'; New = 'Concept: Greetings Time of Day' },
  @{ Old = '<button class="mock-footer-btn" type="button">Continuar</button>'; New = '<button class="mock-footer-btn" type="button">Continue</button>' },
  @{ Old = '<strong>4. Resultado final</strong>'; New = '<strong>4. Final result</strong>' },
  @{ Old = 'Resumo da session ao terminar a unidade.'; New = 'Session summary at the end of the unit.' },
  @{ Old = 'Acertos'; New = 'Correct' },
  @{ Old = 'Erros'; New = 'Errors' },
  @{ Old = 'CoraÃ§Ãµes'; New = 'Hearts' },
  @{ Old = 'Unidade concluÃ­da'; New = 'Unit completed' },
  @{ Old = 'O aluno finaliza com atualizaÃ§Ã£o da trilha, persistence do progresso e possÃ­veis reviews futuras.'; New = 'The learner finishes with a path update, persisted progress, and possible future reviews.' },
  @{ Old = 'Voltar para a trilha'; New = 'Back to the path' },
  @{ Old = '<strong>PersistÃªncia atual:</strong> progresso salvo localmente e em fluxos jÃ¡ preparados para backend/autenticaÃ§Ã£o.'; New = '<strong>Current persistence:</strong> progress saved locally and in flows already prepared for backend authentication.' }
)
Apply-Replacements -Path $grammarPath -Pairs $grammarPairs

$flashPath = "C:\Users\Geovane TI\Documents\english-platform\documentation\en\flashcards-documentation.html"
$flashPairs = @(
  @{ Old = 'com foco em trilha de review, logic SRS inspirada em sistemas modernos de repetiÃ§Ã£o espaÃ§ada, session ativa,'; New = 'with a focus on the review path, SRS logic inspired by modern spaced-repetition systems, and active sessions,' },
  @{ Old = 'resultados analÃ­ticos e integration com My Vocabulary e review global.'; New = 'analytical results, and integration with My Vocabulary and global review.' },
  @{ Old = 'inteligente. Ele trabalha com sessions diÃ¡rias, decks por trilha, cards frÃ¡geis, reforÃ§o adaptativo e'; New = 'smartly. It works with daily sessions, deck-based paths, fragile cards, adaptive reinforcement, and' },
  @{ Old = 'leitura clara de resultados.'; New = 'clear results reading.' },
  @{ Old = 'Trilha por decks'; New = 'Deck-based path' },
  @{ Old = 'SRS por card'; New = 'Per-card SRS' },
  @{ Old = 'Resultados analÃ­ticos'; New = 'Analytical results' },
  @{ Old = 'IntegraÃ§Ã£o com Vocabulary'; New = 'Vocabulary integration' },
  @{ Old = 'IntegraÃ§Ã£o com review global'; New = 'Global review integration' },
  @{ Old = 'Estados por card:'; New = 'Per-card states:' },
  @{ Old = 'new, learning, relearning e review.'; New = 'new, learning, relearning, and review.' },
  @{ Old = 'easy, good, hard e again influenciam o prÃ³ximo intervalo.'; New = 'easy, good, hard, and again influence the next interval.' },
  @{ Old = 'due_at, interval_days, stability_days, difficulty e forgetting_index.'; New = 'due_at, interval_days, stability_days, difficulty, and forgetting_index.' },
  @{ Old = 'filtra a session para focar apenas nos cards frÃ¡geis.'; New = 'filters the session to focus only on fragile cards.' },
  @{ Old = 'Fila dynamic:'; New = 'Dynamic queue:' },
  @{ Old = 'cards errados podem voltar dentro da prÃ³pria session.'; New = 'incorrect cards can return within the same session.' },
  @{ Old = '<strong>1. Escolha do deck</strong>'; New = '<strong>1. Deck selection</strong>' },
  @{ Old = 'O aluno entra na trilha e escolhe o prÃ³ximo deck liberado ou um deck difÃ­cil.'; New = 'The learner enters the path and chooses the next unlocked deck or a difficult deck.' },
  @{ Old = '<strong>2. Review ativa</strong>'; New = '<strong>2. Active review</strong>' },
  @{ Old = 'O card pode ser virado, ouvido, acelerado e respondido com um rating.'; New = 'The card can be flipped, listened to, sped up, and answered with a rating.' },
  @{ Old = '<strong>3. AtualizaÃ§Ã£o do SRS</strong>'; New = '<strong>3. SRS update</strong>' },
  @{ Old = 'Cada resposta atualiza dificuldade, estabilidade e prÃ³xima review.'; New = 'Each answer updates difficulty, stability, and the next review.' },
  @{ Old = '<strong>4. IntegraÃ§Ã£o de vocabulary</strong>'; New = '<strong>4. Vocabulary integration</strong>' },
  @{ Old = '<strong>5. RelatÃ³rio final</strong>'; New = '<strong>5. Final report</strong>' },
  @{ Old = '<strong>Time total:</strong> calculado do primeiro ao last card.'; New = '<strong>Total time:</strong> calculated from the first to the last card.' },
  @{ Old = '<strong>PrecisÃ£o:</strong> score final com destaque visual.'; New = '<strong>Accuracy:</strong> final score with visual emphasis.' },
  @{ Old = '<strong>RevisÃµes prioritÃ¡rias:</strong> quantidade de cards ainda frÃ¡geis.'; New = '<strong>Priority reviews:</strong> number of cards that are still fragile.' },
  @{ Old = 'toggle ON/OFF para atualizar o vocabulary do aluno.'; New = 'ON/OFF toggle to update the learner''s vocabulary.' },
  @{ Old = 'cards frÃ¡geis podem ser enviados para a review espaÃ§ada global.'; New = 'fragile cards can be sent to global spaced review.' },
  @{ Old = '<strong>Profile e Reports:</strong> resultados de session alimentam view consolidada do user.'; New = '<strong>Profile and Reports:</strong> session results feed the user''s consolidated view.' },
  @{ Old = '<strong>Schedule de review:</strong> a trilha informa cards vencendo hoje e prÃ³xima janela de review.'; New = '<strong>Review schedule:</strong> the path shows cards due today and the next review window.' },
  @{ Old = '<strong>Feito hoje:</strong> decks completos no dia sÃ£o bloqueados atis o prÃ³ximo ciclo diÃ¡rio.'; New = '<strong>Done today:</strong> decks completed today are locked until the next daily cycle.' },
  @{ Old = 'alternÃ¢ncia rÃ¡pida para modo de reforÃ§o.'; New = 'quick toggle for reinforcement mode.' },
  @{ Old = '<strong>Status de integration:</strong> toggle visÃ­vel para My Vocabulary.'; New = '<strong>Integration status:</strong> visible toggle for My Vocabulary.' },
  @{ Old = 'Abaixo estÃ£o representaÃ§Ãµes visuais das principais telas do <strong>Flashcards</strong>, recriadas em'; New = 'Below are visual recreations of the main <strong>Flashcards</strong> screens, rebuilt in' },
  @{ Old = '<strong>1. Trilha de decks</strong>'; New = '<strong>1. Deck path</strong>' },
  @{ Old = 'VisÃ£o dos decks com progressÃ£o e indicaÃ§Ã£o do prÃ³ximo passo.'; New = 'View of the decks with progression and next-step indication.' },
  @{ Old = '<div class="mock-node ring">ðŸ—‚</div>'; New = '<div class="mock-node ring">Cards</div>' },
  @{ Old = 'SaudaÃ§Ãµes e introductions'; New = 'Greetings and introductions' },
  @{ Old = '<div class="mock-node">â˜…</div>'; New = '<div class="mock-node">Star</div>' },
  @{ Old = 'Conversas do dia a dia'; New = 'Daily conversations' },
  @{ Old = '<div class="mock-node gray">ðŸ†</div>'; New = '<div class="mock-node gray">Trophy</div>' },
  @{ Old = 'Review de contexto'; New = 'Context review' },
  @{ Old = '<strong>2. Card em review</strong>'; New = '<strong>2. Card under review</strong>' },
  @{ Old = 'Card ativo com audio, texto central e controle de velocidade.'; New = 'Active card with audio, centered text, and speed control.' },
  @{ Old = 'Frente'; New = 'Front' },
  @{ Old = 'Novo card'; New = 'New card' },
  @{ Old = 'Ele trabalha em um hospital.'; New = 'He works in a hospital.' },
  @{ Old = '<button class="mock-audio-btn" type="button">ðŸ”Š</button>'; New = '<button class="mock-audio-btn" type="button">Audio</button>' },
  @{ Old = 'A session avanÃ§a com evaluation de dificuldade apÃ³s o flip.'; New = 'The session advances with difficulty evaluation after the flip.' },
  @{ Old = 'Verso'; New = 'Back' },
  @{ Old = 'Em consolidaÃ§Ã£o'; New = 'Consolidating' },
  @{ Old = '<strong>4. RelatÃ³rio final</strong>'; New = '<strong>4. Final report</strong>' },
  @{ Old = 'PrecisÃ£o'; New = 'Accuracy' },
  @{ Old = 'Time total'; New = 'Total time' },
  @{ Old = 'PrioritÃ¡rios'; New = 'Priority' },
  @{ Old = '<strong>PersistÃªncia:</strong> progresso salvo por deck, por card e por resultados de session.'; New = '<strong>Persistence:</strong> progress saved by deck, by card, and by session results.' },
  @{ Old = 'O Flashcards estÃ¡ documentado para demonstrar claramente trilha, session ativa, SRS, integration com vocabulary'; New = 'Flashcards is documented to clearly demonstrate the path, active sessions, SRS, integration with vocabulary' },
  @{ Old = 'e relatÃ³rio final analÃ­tico.'; New = 'and the final analytical report.' }
)
Apply-Replacements -Path $flashPath -Pairs $flashPairs

$enginesPath = "C:\Users\Geovane TI\Documents\english-platform\documentation\en\pedagogical-engines-documentation.html"
$enginesPairs = @(
  @{ Old = '<h1>Motores PedagÃ³gicos da Plataforma</h1>'; New = '<h1>Pedagogical Engines of the Platform</h1>' },
  @{ Old = 'responsÃ¡veis por personalizaÃ§Ã£o, review inteligente, diagnÃ³stico, planejamento, retenÃ§Ã£o e leitura global'; New = 'responsible for personalization, intelligent review, diagnosis, planning, retention, and a global reading' },
  @{ Old = 'da evoluÃ§Ã£o do aluno.'; New = 'of learner progress.' },
  @{ Old = 'DiagnÃ³stico adaptativo'; New = 'Adaptive diagnostics' },
  @{ Old = 'Plano semanal automÃ¡tico'; New = 'Automatic weekly plan' },
  @{ Old = 'Caderno de erros'; New = 'Error notebook' },
  @{ Old = 'RetenÃ§Ã£o 7/30 dias'; New = '7/30-day retention' },
  @{ Old = 'RelatÃ³rios pedagÃ³gicos'; New = 'Pedagogical reports' },
  @{ Old = 'Diferente dos mÃ³dulos de content, estes motores atuam por trÃ¡s da experiÃªncia do aluno. Eles analisam'; New = 'Unlike content modules, these engines work behind the learner experience. They analyze' },
  @{ Old = 'comportamento, priorizam review, detectam patterns de erro, montam rotinas e apresentam uma view global'; New = 'behavior, prioritize review, detect error patterns, build routines, and present a global view' },
  @{ Old = 'do processo de learning.'; New = 'of the learning process.' },
  @{ Old = '<strong>1. Coleta</strong>'; New = '<strong>1. Data collection</strong>' },
  @{ Old = 'Os motores consolidam erros, retenÃ§Ã£o, habilidade, progresso e metas.'; New = 'The engines consolidate errors, retention, skill, progress, and goals.' },
  @{ Old = 'As recomendaÃ§Ãµes alteram review, plano semanal, foco do aluno e prÃ³ximos passos.'; New = 'Recommendations change the review queue, weekly plan, learner focus, and next steps.' },
  @{ Old = '<h2>Cenas do Sistema</h2>'; New = '<h2>System Scenes</h2>' },
  @{ Old = 'Abaixo estÃ£o representaÃ§Ãµes visuais das telas e painisis que simbolizam os motores pedagÃ³gicos da plataforma,'; New = 'Below are visual recreations of the screens and panels that represent the platform''s pedagogical engines,' },
  @{ Old = 'recriados em HTML/CSS para documentation.'; New = 'rebuilt in HTML/CSS for documentation.' },
  @{ Old = '<strong>1. Menu lateral de motores</strong>'; New = '<strong>1. Engine side menu</strong>' },
  @{ Old = 'VisÃ£o dos painisis tiscnicos/pedagÃ³gicos concentrados em uma mesma Ã¡rea.'; New = 'View of the technical and pedagogical panels concentrated in one area.' },
  @{ Old = 'Teste inicial, meta e trilha personalizada.'; New = 'Initial test, goal, and personalized path.' },
  @{ Old = 'Resumo avanÃ§ado de progresso, retenÃ§Ã£o e foco.'; New = 'Advanced summary of progress, retention, and focus.' },
  @{ Old = 'Resumo de itens prioritÃ¡rios e origem dos reforÃ§os.'; New = 'Summary of priority items and the origin of reinforcements.' },
  @{ Old = 'ReforÃ§o recomendado hoje'; New = 'Recommended reinforcement today' },
  @{ Old = '3 conceitos frÃ¡geis aguardando reforÃ§o.'; New = '3 fragile concepts waiting for reinforcement.' },
  @{ Old = '11 cards prioritÃ¡rios vindos das Ãºltimas sessions.'; New = '11 priority cards coming from the latest sessions.' },
  @{ Old = '5 palavras novas marcadas para retenÃ§Ã£o.'; New = '5 new words marked for retention.' },
  @{ Old = '<strong>3. DiagnÃ³stico e planejamento</strong>'; New = '<strong>3. Diagnostics and planning</strong>' },
  @{ Old = 'Goal atual: ConversaÃ§Ã£o'; New = 'Current goal: Conversation' },
  @{ Old = 'Skill score dominante'; New = 'Dominant skill score' },
  @{ Old = 'Vocabulary alto, Grammar medium, Speaking em reforÃ§o.'; New = 'Vocabulary high, Grammar medium, Speaking under reinforcement.' },
  @{ Old = 'Plano da semana'; New = 'Weekly plan' },
  @{ Old = 'Segunda: Grammar | Quarta: Listening | Sexta: Speaking.'; New = 'Monday: Grammar | Wednesday: Listening | Friday: Speaking.' },
  @{ Old = '<strong>4. RelatÃ³rio consolidado</strong>'; New = '<strong>4. Consolidated report</strong>' },
  @{ Old = 'Visual summary do desempenho pedagÃ³gico do aluno.'; New = 'Visual summary of the learner''s pedagogical performance.' },
  @{ Old = 'RetenÃ§Ã£o'; New = 'Retention' },
  @{ Old = 'Erros recorrentes'; New = 'Recurring errors' },
  @{ Old = 'Foco atual'; New = 'Current focus' },
  @{ Old = '<strong>Scope:</strong> esta documentation centraliza os menus pedagÃ³gicos tiscnicos da plataforma em um Ãºnico lugar.'; New = '<strong>Scope:</strong> this documentation centralizes the platform''s technical pedagogical menus in one place.' },
  @{ Old = '<strong>Strategic reading:</strong> este conjunto is importante para apresentar personalizaÃ§Ã£o e valor pedagÃ³gico ao produto.'; New = '<strong>Strategic reading:</strong> this set is important for presenting personalization and pedagogical value in the product.' },
  @{ Old = 'a retenÃ§Ã£o real do aluno.'; New = 'for real learner retention.' }
)
Apply-Replacements -Path $enginesPath -Pairs $enginesPairs
