$files = Get-ChildItem -Path "C:\Users\Geovane TI\Documents\english-platform\documentation\en" -Filter *.html

$replacements = @(
  @{ Old = "Documentation for the module Community, com feed limpo, interacoes locais, moderacao e notificacoes."; New = "Documentation for the Community module, with a clean feed, local interactions, moderation, and notifications." },
  @{ Old = "Documentation for the module Dictionary, usado para consulta detalhada de palavras com significados, classes gramaticais, IPA, exemplos e audio."; New = "Documentation for the Dictionary module, used for detailed word lookup with meanings, grammatical classes, IPA, examples, and audio." },
  @{ Old = "Documentation for the module Listening, com temas, frases em sequencia, autoplay, repeat, sotaques e velocidades controladas."; New = "Documentation for the Listening module, with themed practice, sequential phrases, autoplay, repeat, accents, and controlled speeds." },
  @{ Old = "Documentation for the module Music, desenhado para usar musica como motor de aprendizado com video, letra, traducao e audio por linha."; New = "Documentation for the Music module, designed to use music as a learning driver with video, lyrics, translation, and line-by-line audio." },
  @{ Old = "Documentation for the module Games, estruturado para treino rapido, competitivo e viciante com reaproveitamento inteligente de erros do aluno."; New = "Documentation for the Games module, structured for fast, competitive, and engaging practice with smart reuse of learner mistakes." },
  @{ Old = "Documentation for the module Modern Methodologies, que funciona como mentor inteligente para melhoria avancada do ingles por categoria e objetivo."; New = "Documentation for the Modern Methodologies module, which works as an intelligent mentor for advanced English improvement by category and goal." },
  @{ Old = "Documentation for the module Profile, responsavel por consolidar identidade, historico, metas, badges e leitura geral da jornada do aluno."; New = "Documentation for the Profile module, responsible for consolidating identity, history, goals, badges, and the overall reading of the learner journey." },
  @{ Old = "Documentation for the module Pronounce, voltado para pratica de sons, feedback fonetico, score de fala e orientacao articulatoria."; New = "Documentation for the Pronounce module, focused on sound practice, phonetic feedback, speech scoring, and articulation guidance." },
  @{ Old = "Documentation for the module Reading, focado em leitura por nivel, perguntas de compreensao, glossario contextual e explicacao por erro."; New = "Documentation for the Reading module, focused on level-based reading, comprehension questions, contextual glossary, and error explanation." },
  @{ Old = "Documentation for the module Speak With AI, projetado para simulacao de conversa, correcao contextual, leitura em voz alta e expansao de vocabulario."; New = "Documentation for the Speak With AI module, designed for conversation simulation, contextual correction, read-aloud support, and vocabulary expansion." },
  @{ Old = "Documentation for the module Speak With Natives, com lista de nativos, chamada de video, chat lateral, agenda e recursos de seguranca."; New = "Documentation for the Speak With Natives module, with a list of native speakers, video calls, side chat, scheduling, and safety features." },
  @{ Old = "Documentation for the module Writing, focado em escrita progressiva, montagem de frase, correcao, reescrita e feedback de estilo e clareza."; New = "Documentation for the Writing module, focused on progressive writing, sentence building, correction, rewriting, and style and clarity feedback." },
  @{ Old = "Documentation for the module Test Your English Level, criado para avaliar listening, reading, speaking e writing com resultado final e nivel estimado."; New = "Documentation for the Test Your English Level module, created to assess listening, reading, speaking, and writing with a final result and estimated level." },
  @{ Old = "Documentation for the module Translation Practice, focado em traducao ativa com validacao semantica, contexto e mistura EN-PT e PT-EN."; New = "Documentation for the Translation Practice module, focused on active translation with semantic validation, context, and EN-PT / PT-EN practice." },
  @{ Old = "Documentation for the module"; New = "Documentation for the" },
  @{ Old = "Goal do MÃ³dulo"; New = "Module Goal" },
  @{ Old = "O que ele cobre hoje"; New = "What It Covers Today" },
  @{ Old = "Motor de RevisÃ£o"; New = "Review Engine" },
  @{ Old = "Fluxo da SessÃ£o"; New = "Session Flow" },
  @{ Old = "Resultados e MÃ©tricas"; New = "Results and Metrics" },
  @{ Old = "IntegraÃ§Ãµes"; New = "Integrations" },
  @{ Old = "Controles de Trilha"; New = "Path Controls" },
  @{ Old = "Cenas do MÃ³dulo"; New = "Module Scenes" },
  @{ Old = "ObservaÃ§Ãµes de ImplementaÃ§Ã£o"; New = "Implementation Notes" },
  @{ Old = "Tipos de ExercÃ­cio"; New = "Exercise Types" },
  @{ Old = "Fluxo da LiÃ§Ã£o"; New = "Lesson Flow" },
  @{ Old = "Feedback PedagÃ³gico"; New = "Pedagogical Feedback" },
  @{ Old = "InteligÃªncia PedagÃ³gica"; New = "Pedagogical Intelligence" },
  @{ Old = "O que esta documentaÃ§Ã£o cobre"; New = "What This Documentation Covers" },
  @{ Old = "Leitura pedagÃ³gica"; New = "Pedagogical reading" },
  @{ Old = "AÃ§Ã£o"; New = "Action" },
  @{ Old = "Painel de revisÃ£o global"; New = "Global review panel" },
  @{ Old = "Leitura estratÃ©gica:"; New = "Strategic reading:" },
  @{ Old = "Escopo:"; New = "Scope:" },
  @{ Old = "revisÃ£o"; New = "review" },
  @{ Old = "integraÃ§Ã£o"; New = "integration" },
  @{ Old = "sessÃ£o"; New = "session" },
  @{ Old = "sessÃµes"; New = "sessions" },
  @{ Old = "lÃ³gica"; New = "logic" },
  @{ Old = "prÃ¡tica"; New = "practice" },
  @{ Old = "correÃ§Ã£o"; New = "correction" },
  @{ Old = "padrÃµes"; New = "patterns" },
  @{ Old = "usuÃ¡rio"; New = "user" },
  @{ Old = "usuÃ¡rios"; New = "users" },
  @{ Old = "manhÃ£"; New = "morning" },
  @{ Old = "coraÃ§Ãµes"; New = "hearts" },
  @{ Old = "liÃ§Ã£o"; New = "lesson" },
  @{ Old = "nÃ­veis"; New = "levels" },
  @{ Old = "nÃ­vel"; New = "level" },
  @{ Old = "fonÃ©tico"; New = "phonetic" },
  @{ Old = "vocabulÃ¡rio"; New = "vocabulary" },
  @{ Old = "mÃ©dio"; New = "medium" },
  @{ Old = "mÃ©tricas"; New = "metrics" },
  @{ Old = "visÃ£o"; New = "view" },
  @{ Old = "explicaÃ§Ã£o"; New = "explanation" },
  @{ Old = "avaliaÃ§Ã£o"; New = "evaluation" },
  @{ Old = "dinÃ¢mica"; New = "dynamic" },
  @{ Old = "Ã¡udio"; New = "audio" },
  @{ Old = "documentaÃ§Ã£o"; New = "documentation" },
  @{ Old = "implementaÃ§Ã£o"; New = "implementation" },
  @{ Old = "persistÃªncia"; New = "persistence" },
  @{ Old = "interaÃ§Ãµes"; New = "interactions" },
  @{ Old = "seguranÃ§a"; New = "safety" },
  @{ Old = "configuraÃ§Ãµes"; New = "settings" },
  @{ Old = "traduÃ§Ã£o"; New = "translation" },
  @{ Old = "introduÃ§Ãµes"; New = "introductions" },
  @{ Old = "saudaÃ§Ãµes"; New = "greetings" },
  @{ Old = "revisÃµes"; New = "reviews" },
  @{ Old = "conteÃºdo"; New = "content" },
  @{ Old = "Ãºltimo"; New = "last" },
  @{ Old = "nÃ£o"; New = "not" },
  @{ Old = "Ã©"; New = "is" },
  @{ Old = "COMEÃ‡AR"; New = "START" }
)

foreach ($file in $files) {
  $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
  foreach ($replacement in $replacements) {
    $content = $content.Replace($replacement.Old, $replacement.New)
  }
  [System.IO.File]::WriteAllText($file.FullName, $content, [System.Text.Encoding]::UTF8)
}
